USE master;
GO

IF DB_ID(N'BD2_TPI_TIENDA_INDUMENTARIA') IS NOT NULL
BEGIN
    ALTER DATABASE BD2_TPI_TIENDA_INDUMENTARIA SET SINGLE_USER WITH ROLLBACK IMMEDIATE;
    DROP DATABASE BD2_TPI_TIENDA_INDUMENTARIA;
END
GO

CREATE DATABASE BD2_TPI_TIENDA_INDUMENTARIA;
GO

USE BD2_TPI_TIENDA_INDUMENTARIA;
GO

--Plasmemos aca los scripts de creacion de las tablas.

SELECT 'Base de datos creada OK...' AS Resultado;
GO